repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 97a46d97aea9f027a3a8714244f5c93a74d742de
  hooks:
  - id: pretty-format-golang
    args: [--autofix]
